server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
#      default-filters: # 全局通用过滤器
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service              #灵活的路由地址匹配
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            - After=2023-11-20T17:38:13.586918800+08:00[Asia/Shanghai] # 在此时间后才可以访问
            - Cookie=name,blh # 必须要有Cookie这个属性，并且name的值必须是blh
            - Header=X-Request-Id, \d+ # 请求头中要有X-Request-Id属性并且值为整数的正则表达式
            - Host=**.atguigu.com # 主机地址中，必须包含 atguigu.com
            - Path=/pay/** # 访问路径中必须是以/pay/开始
            - Query=userName, \d+ # 带查询参数，参数为数字，正则表达式
#            - RemoteAddr=192.168.1.1/24 #外部访问此服务的Ip限制，最大跨度不能超过32，目前是1~24
            - Method=GET,POST,DELETE
            - My=diamond # 支持短促格式 值必须是diamond，其他值无效
#            - name: My # 自定义断言，名称为My
#              args:
#                userType: diamond # 必须包含参数userType,value为diamond

        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service              #灵活的路由地址匹配
          predicates:
            - Path=/pay/gateway/info/**
        - id: pay_routh3 # 断言，路径相匹配的进行路由
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/filter/** # 真实地址
#            - Path=/gateway/filter/**
#            - Path=/XYZ/abc/{segment} # 断言，配合测试，{segment}最终将被setPath取代
          filters: # 添加网关过滤器
            - My=atguigu # 自定义过滤器配置
#            - AddRequestHeader=X-Request-atguigu1,value1 # 请求头过滤器 作用是在访问的请求头中添加上yml文件中配置的值
#            - AddRequestHeader=X-Request-atguigu2,value2 # 请求头过滤器
#            - RemoveRequestHeader=x-request-id # 删除请求头中的值
#            - SetRequestHeader=X-Request-atguigu2,changeValue # 修改请求头中的值
#            - AddRequestParameter=customerId,9527 # 新增请求参数parameter, k, v
#            - RemoveRequestParameter=customerName # 删除请求参数parameter, k, v
#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数 X-Response-atguigu,并设置值为BlueResponse
#            - SetResponseHeader=Date, 2099-11-11 # 将response中Date的值设置为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将response中的content-type删除
#            - SetPath=/gateway/{segment} # 占位符替换为上方的地址
#            - PrefixPath=/pay # 在访问的路径前添加上/pay 客户端请求路径为不包含/pay的请求路径
#            - Redirect=/pay # 在访问的路径前添加上/pay 客户端请求路径为不包含/pay的请求路径
#            - RedirectTo=302,http://www.baidu.com/ # 访问/pay/gateway/filter/**时，会重定向跳转到baidu